[package]
name        = "aoc2021rust"
description = ""
edition     = "2018"
version     = "0.1.0"
authors     = ["crvdgc <ubikium@gmail.com>"]
repository  = "https://github.com/crvdgc/aoc2021rust"
include = ["src/**/*"]

[dependencies]
itertools = "0.10.0"

[dev-dependencies]

